apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknad-kontantstotte-api
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: navikt/soknad-kontantstotte-api:{{version}}
  port: 8080
  liveness:
    path: /internal/status/isAlive
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  ingresses:
    - "https://soknad-kontantstotte-api-q.nav.no"
  vault:
    enabled: true
  resources:
    limits:
      memory: 2Gi
      cpu: 1500m
    requests:
      memory: 1Gi
      cpu: 1000m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
