cors:
  allowed_origins:
    - "https://soknad-kontantstotte.nav.no"
    - "https://soknad-kontantstotte-gcp.intern.nav.no"

# Api-gw/tjenester i FSS
FAMILIE_KS_MOTTAK_API_URL: https://familie-ks-mottak.prod-fss-pub.nais.io/api/
FAMILIE_KS_MOTTAK_AUDIENCE: prod-fss:teamfamilie:familie-ks-mottak

# Annet
ENVIRONMENT_NAME: p

# familie-dokument i dev-GCP
FAMILIE_DOKUMENT_API_URL: "https://familie-dokument.nav.no/familie/dokument/api"

#PDL
PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default
PDL_AUDIENCE: prod-fss:pdl:pdl-api
