cors:
  allowed_origins:
    - "https://soknad-kontantstotte.nav.no"

# Api-gw/tjenester i FSS
FAMILIE_KS_MOTTAK_API_URL: https://familie-ks-mottak-teamfamilie.prod-fss-pub.nais.io/api/
FAMILIE_KS_MOTTAK_AUDIENCE: prod-fss:teamfamilie:familie-ks-mottak

FAMILIE_DOKUMENT_AUDIENCE: prod-gcp:teamfamilie:familie-dokument
# Annet
ENVIRONMENT_NAME: p

# familie-dokument i GCP
FAMILIE_DOKUMENT_API_URL: "https://www.nav.no/familie/dokument/api"

#PDL
PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default
PDL_AUDIENCE: prod-fss:pdl:pdl-api
