spring:
  main:
    allow-bean-definition-overriding: true

UNLEASH_API_URL: http://localhost
NAIS_APP_NAME: soknad-kontantstotte-api

SOKNAD_HTML_GENERATOR_URL: http://localhost:9000/api/

SOKNAD_KONTANTSTOTTE_API_FAMILIE_KS_MOTTAK_APIKEY_USERNAME: anything
SOKNAD_KONTANTSTOTTE_API_FAMILIE_KS_MOTTAK_APIKEY_PASSWORD: anything

FAMILIE_KS_MOTTAK_API_URL: "http://familie-ks-mottak:8084/api/"
CREDENTIAL_USERNAME: "srv-soknad-kontantstotte-api"
CREDENTIAL_PASSWORD: "skal-ikke-sjekkes-inn"

http.proxy:

logging:
  level:
    no.finn.unleash: ERROR
    org.eclipse.jetty: INFO
    org.springframework: INFO
    org.glassfish.jersey: INFO
    org.glassfish.jersey.logging.LoggingFeature: DEBUG
    com.fasterxml: WARN
  config: classpath:logback-spring.xml

FAMILIE_DOKUMENT_API_URL: "http://localhost:8082/api/"
PDL_URL: http://familie-mock-server:1337/rest/api/pdl/