no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    acceptedaudience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookie_name: selvbetjening-idtoken

# Appdynamics
APPDYNAMICS_AGENT_ACCOUNT_NAME: NON-PROD
APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY} #Ligger i vault

# Enonic
APPRES_CMS_URL: https://appres-q2.nav.no

# Loadbalancer/ingress
LOADBALANCER_SOKNAD_KONTANTSTOTTE_API_URL: soknad-kontantstotte-api-q.nav.no

# Pdf-generator
SOKNAD_HTML_GENERATOR_URL: https://soknad-html-generator.intern.dev.nav.no/api/

# Api-gw/tjenester i FSS
FAMILIE_KS_MOTTAK_API_URL: https://api-gw-q0.oera.no/familie-ks-mottak/api/
TPS-PROXY_API_V1_INNSYN_URL: https://api-gw-q2.oera.no/tps-proxy/api/v1/innsyn/

# S3
SOKNAD_KONTANTSTOTTE_API_S3_CREDENTIAL_USERNAME: ${SOKNAD_KONTANTSTOTTE_API_S3_CREDENTIAL_USERNAME} #Ligger i vault

# Annet
ENVIRONMENT_NAME: q

# familie-dokument i dev-GCP
FAMILIE_DOKUMENT_API_URL: "https://familie-dokument.dev.intern.nav.no/api/"