apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknad-kontantstotte-api
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  team: teamfamilie
  port: 8080
  envFrom:
    - configmap: loginservice-idporten
    - secret: {{secret}}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 50
    timeout: 5
    periodSeconds: 10     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
  readiness:
    path: /internal/status/isAlive
    initialDelay: 50
    timeout: 5
    periodSeconds: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 500m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: soknad-kontantstotte
    outbound:
      rules:
        - application: familie-dokument
        - application: soknad-html-generator
      external:
        - host: navtestb2c.b2clogin.com
        - host: webproxy-nais.nav.no
  idporten:
    enabled: true
    # optional, default shown
    clientURI: "https://nav.no"
    # optional, default shown
    redirectPath: "/oauth2/callback"
    # optional, default shown
    frontchannelLogoutPath: "/oauth2/logout"
    # optional, defaults shown
    postLogoutRedirectURIs:
      - "https://nav.no"
    # optional, in seconds - defaults shown (1 hour)
    accessTokenLifetime: 3600
    # optional, in seconds - defaults shown (2 hours)
    sessionLifetime: 7200
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring_profile}}
    - name: APP_TEAM
      value: teamfamilie